// sample/react/src/components/HelloWorld.tsx
import { Atom, useAtomSet, useAtomValue } from "@effect-atom/atom-react"
import { memo, useEffect, useMemo, useState } from "react"
import { TestClient } from "../fixtures/TestClient"
import { Exit } from "effect"

const INTERVAL_DURATION = 1_000
const countAtom = Atom.make(0)

// separate component to visualize that only this part re-renders on count change
// memo to prevent re-renders when the parent re-renders
// use react-scan to see the visualization
const Counter = memo(function Counter() {
  const count = useAtomValue(countAtom)
  const setCount = useAtomSet(countAtom)
  return (
    <button onClick={() => setCount((count) => count + 1)}>
      count is {count}
    </button>
  )
})

export function HelloWorld() {
  const [intervalEnabled, setIntervalEnabled] = useState(false)
  const [value, setValue] = useState({
    echo: "initial",
    state: "",
    at: new Date(),
  })

  const queryAtom = useMemo(() => {
    return TestClient.query("Get", value, {
      reactivityKeys: ["Get"],
    })
      .pipe(Atom.refreshOnWindowFocus)
      .pipe(
        Atom.map((res) => {
          console.log("Got query result", res)
          return res
        }),
      )
  }, [value])

  const result = useAtomValue(queryAtom)

  const set = useAtomSet(TestClient.mutation("Set"), {
    mode: "promiseExit",
  })

  const onSet = () => {
    set({
      payload: { state: "state " + new Date().toISOString() },
      reactivityKeys: ["Get"],
    }).then((_) =>
      console.log(
        "finished",
        Exit.match(_, {
          onSuccess: (_) => ({ success: _ }),
          onFailure: (_) => ({ failure: _ }),
        }),
      ),
    )
  }

  useEffect(() => {
    if (!intervalEnabled) return

    const interval = setInterval(() => {
      setValue({
        echo: `Hello World ${new Date().toLocaleTimeString()}`,
        state: "",
        at: new Date(),
      })
    }, INTERVAL_DURATION)

    return () => clearInterval(interval)
  }, [intervalEnabled])

  return (
    <>
      {result._tag === "Initial" && <div>Initial</div>}
      {result._tag === "Failure" && (
        <div>
          {result.waiting && <div>Waiting...</div>}
          Failure.. {String(result.cause)}
        </div>
      )}
      {result._tag === "Success" && (
        <div>
          {result.waiting && <div>Waiting...</div>}
          Success: {JSON.stringify(result.value)}
        </div>
      )}

      <button onClick={onSet}>Set State</button>
      <button onClick={() => setIntervalEnabled(!intervalEnabled)}>
        Set Interval {intervalEnabled ? "OFF" : "ON"}
      </button>

      <div className="card">
        <Counter />
      </div>
    </>
  )
}

// sample/vue/src/components/HelloWorld.vue
<script setup lang="ts">
import { Atom, useAtomSet, useAtomValue } from "@effect-atom/atom-vue"
import { onUnmounted, ref } from "vue"
import { TestClient } from "../fixtures/TestClient";
import { Exit } from "effect";

defineProps<{ msg: string }>()

const count = ref(0)

const req = ref({ echo: "Hello World" })

const result = useAtomValue(() => {
  console.log("Computing Atom:", req.value)
  return Atom.refreshOnWindowFocus(TestClient.query("Get", req.value, { reactivityKeys: ["Get"]}))
})

const set = useAtomSet(() => TestClient.mutation("Set"), { mode: "promiseExit" })

const intervalEnabled = ref(false)

const interval = setInterval(
  () =>
    intervalEnabled.value &&
    (req.value = { echo: `Hello World ${new Date().toLocaleTimeString()}` }),
  5_000,
)
const onSet = () => set({ payload: { state: "state "+ new Date().toISOString() }, reactivityKeys: ["Get"] })
  .then(_ => console.log("finished", Exit.match(_, { onSuccess: _ => ({ success: _ }), onFailure: _ => ({ failure: _})})))
onUnmounted(() => clearInterval(interval))
</script>

<template>
  <h1>{{ msg }}</h1>

  <div v-if="result._tag === 'Initial'">Initial</div>
  <div v-else-if="result._tag === 'Failure'">
    <div v-if="result.waiting">Waiting...</div>
    Failure.. {{ result.cause }}
  </div>
  <div v-else>
    <div v-if="result.waiting">Waiting...</div>
    Success: {{ result.value }}
  </div>

  <button @click="onSet">Set state</button>

  <button @click="intervalEnabled = !intervalEnabled">
    Toggle interval {{ !intervalEnabled ? "ON" : "OFF" }}
  </button>

  <div class="card">
    <button type="button" @click="count++">count is {{ count }}</button>
    <p>
      Edit
      <code>components/HelloWorld.vue</code> to test HMR
    </p>
  </div>

  <p>
    Check out
    <a href="https://vuejs.org/guide/quick-start.html#local" target="_blank"
      >create-vue</a
    >, the official Vue + Vite starter
  </p>
  <p>
    Learn more about IDE Support for Vue in the
    <a
      href="https://vuejs.org/guide/scaling-up/tooling.html#ide-support"
      target="_blank"
      >Vue Docs Scaling up Guide</a
    >.
  </p>
  <p class="read-the-docs">Click on the Vite and Vue logos to learn more</p>
</template>

<style scoped>
.read-the-docs {
  color: #888;
}
</style>
